AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - 'app/admin/**/*'
