default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: screenshot_receiver_development

test:
  <<: *default
  database: screenshot_receiver_test

production:
  <<: *default
  database: screenshot_receiver_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
